import { Router } from 'express';
import { requireAuth } from '../../middleware/auth.middleware.js';
import { validate } from '../../middleware/validate.middleware.js';
import { getDashboard, getUserStats, getBloqueStats, getRepasoStats, getSimulacrosStats, getEvolucion, getRacha, getRachaBloques, getResumenOposicion, getProgresoBloques, getProgresoBloquesByTema, getDetalleBloque, getMisOposiciones, getObjetivoDiario, getGamificacion, getFocoHoy, getResumenSemana, getActividad14Dias, getTemasDebiles, getProgresoTemas, getProgresoTemasReal, getInsightMensual, getProgresoSemanal, getEficienciaTiempo, getBalancePrecision, getRitmoPregunta, getConsistenciaDiaria } from '../../controllers/stats.controller.js';
import { getRanking, getProgresoTemaReal } from '../../controllers/statsProgresoTema.controller.js';
import { bloqueStatsQuerySchema, repasoStatsQuerySchema, simulacrosStatsQuerySchema, evolucionQuerySchema } from '../../schemas/stats.schema.js';

const router = Router();

router.get('/dashboard', requireAuth, getDashboard);
router.get('/consistencia-diaria', requireAuth, getConsistenciaDiaria);
router.get('/ritmo-pregunta', requireAuth, getRitmoPregunta);
router.get('/balance-precision', requireAuth, getBalancePrecision);
router.get('/eficiencia-tiempo', requireAuth, getEficienciaTiempo);
router.get('/progreso-semanal', requireAuth, getProgresoSemanal);
router.get('/insight-mensual', requireAuth, getInsightMensual);
router.get('/temas-debiles', requireAuth, getTemasDebiles);
router.get('/progreso-temas', requireAuth, getProgresoTemas);
router.get('/progreso-temas-real', requireAuth, getProgresoTemasReal);
router.get('/progreso-tema-real', requireAuth, getProgresoTemaReal);
router.get('/actividad-14dias', requireAuth, getActividad14Dias);
router.get('/resumen-semana', requireAuth, getResumenSemana);
router.get('/foco-hoy', requireAuth, getFocoHoy);
router.get('/objetivo-diario', requireAuth, getObjetivoDiario);
router.get('/gamificacion', requireAuth, getGamificacion);
router.get('/user', requireAuth, getUserStats);
router.get('/bloque', requireAuth, validate(bloqueStatsQuerySchema, 'query'), getBloqueStats);
router.get('/repaso', requireAuth, validate(repasoStatsQuerySchema, 'query'), getRepasoStats);
router.get('/simulacros', requireAuth, validate(simulacrosStatsQuerySchema, 'query'), getSimulacrosStats);
router.get('/evolucion', requireAuth, validate(evolucionQuerySchema, 'query'), getEvolucion);
router.get('/racha', requireAuth, getRacha);
router.get('/racha-bloques', requireAuth, getRachaBloques);
router.get('/resumen-oposicion', requireAuth, getResumenOposicion);
router.get('/progreso-bloques', requireAuth, getProgresoBloques);
router.get('/progreso-bloques-tema', requireAuth, getProgresoBloquesByTema);
router.get('/bloque/:id/detalle', requireAuth, getDetalleBloque);
router.get('/mis-oposiciones', requireAuth, getMisOposiciones);
router.get('/ranking', requireAuth, getRanking);

export default router;
