import { apiRequest } from './api';

export const testApi = {
  generate: (token, payload) => apiRequest('/tests/generate', { method: 'POST', body: payload, token }),
  generateRefuerzo: (token, payload) => apiRequest('/tests/generate-refuerzo', { method: 'POST', body: payload, token }),
  getRecommended: (token) => apiRequest('/tests/recomendado', { token }),
  getConsistenciaDiaria: (token) => apiRequest('/stats/consistencia-diaria', { token }),
  getFocoHoy: (token) => apiRequest('/stats/foco-hoy', { token }),
  getResumenSemana: (token) => apiRequest('/stats/resumen-semana', { token }),
  getActividad14Dias: (token) => apiRequest('/stats/actividad-14dias', { token }),
  getTemasDebiles: (token) => apiRequest('/stats/temas-debiles', { token }),
  getProgresoTemas: (token, oposicionId) => apiRequest('/stats/progreso-temas', { token, query: oposicionId ? { oposicion_id: oposicionId } : {} }),
  getInsightMensual: (token) => apiRequest('/stats/insight-mensual', { token }),
  getRendimientoModos: (token) => apiRequest('/stats/rendimiento-modos', { token }),
  getProgresoSemanal: (token) => apiRequest('/stats/progreso-semanal', { token }),
  getEficienciaTiempo: (token) => apiRequest('/stats/eficiencia-tiempo', { token }),
  getRitmoPregunta: (token) => apiRequest('/stats/ritmo-pregunta', { token }),
  getBalancePrecision: (token) => apiRequest('/stats/balance-precision', { token }),
  submit: (token, payload) => apiRequest('/tests/submit', { method: 'POST', body: payload, token }),
  history: (token, params = {}) => apiRequest('/tests/history', { token, query: params }),
  userStats: (token) => apiRequest('/stats/user', { token }),
  temaStats: (token, temaId) => apiRequest('/stats/tema', { token, query: { tema_id: temaId } }),
  repasoStats: (token, temaId) => apiRequest('/stats/repaso', { token, query: { tema_id: temaId } }),
  simulacroStats: (token, oposicionId) => apiRequest('/stats/simulacros', { token, query: { oposicion_id: oposicionId } }),
  getDashboard: (token) => apiRequest('/stats/dashboard', { token }),
  getObjetivoDiario: (token) => apiRequest('/stats/objetivo-diario', { token }),
  getGamificacion: (token) => apiRequest('/stats/gamificacion', { token }),
  getRacha: (token) => apiRequest('/stats/racha', { token }),
  getRachaTemas: (token) => apiRequest('/stats/racha-temas', { token }),
  getResumenOposicion: (token, oposicionId) => apiRequest('/stats/resumen-oposicion', { token, query: { oposicion_id: oposicionId } }),
  getProgresoMaterias: (token, oposicionId) => apiRequest('/stats/progreso-materias', { token, query: { oposicion_id: oposicionId } }),
  getProgresoTemasByMateria: (token, materiaId) => apiRequest('/stats/progreso-temas-materia', { token, query: { materia_id: materiaId } }),
  getDetalleTema: (token, temaId) => apiRequest(`/stats/tema/${temaId}/detalle`, { token }),
  getMisOposiciones: (token) => apiRequest('/stats/mis-oposiciones', { token }),
  evolucionStats: (token, limit = 30) => apiRequest('/stats/evolucion', { token, query: { limit } }),
  getRepasoPendientes: (token, limit = 20) => apiRequest('/repaso/pendientes', { token, query: { limit } }),
  getReview: (token, testId) => apiRequest(`/tests/${testId}/review`, { token }),
  getConfig: (token, testId) => apiRequest(`/tests/${testId}/config`, { token }),
};