import { apiRequest } from './api';

export const testApi = {
  generate: (token, payload) => apiRequest('/tests/generate', { method: 'POST', body: payload, token }),
  generateDemo: (token, oposicionId) => apiRequest('/tests/generate-demo', { method: 'POST', body: { oposicionId }, token }),
  generateRefuerzo: (token, payload) => apiRequest('/tests/generate-refuerzo', { method: 'POST', body: payload, token }),
  getRecommended: (token) => apiRequest('/tests/recomendado', { token }),
  getContinuar: (token) => apiRequest('/tests/continuar', { token }),
  getPendientes: (token) => apiRequest('/tests/pendientes', { token }),
  cerrar: (token, testId) => apiRequest(`/tests/${testId}/cerrar`, { method: 'POST', token }),
  getConsistenciaDiaria: (token) => apiRequest('/stats/consistencia-diaria', { token }),
  getFocoHoy: (token) => apiRequest('/stats/foco-hoy', { token }),
  getResumenSemana: (token) => apiRequest('/stats/resumen-semana', { token }),
  getActividad14Dias: (token) => apiRequest('/stats/actividad-14dias', { token }),
  getTemasDebiles: (token) => apiRequest('/stats/temas-debiles', { token }),
  getProgresoTemas: (token, oposicionId) => apiRequest('/stats/progreso-temas', { token, query: oposicionId ? { oposicion_id: oposicionId } : {} }),
  getProgresoTemasReal: (token, oposicionId) => apiRequest('/stats/progreso-temas-real', { token, query: oposicionId ? { oposicion_id: oposicionId } : {} }),
  getInsightMensual: (token) => apiRequest('/stats/insight-mensual', { token }),
  getRendimientoModos: (token) => apiRequest('/stats/rendimiento-modos', { token }),
  getProgresoSemanal: (token) => apiRequest('/stats/progreso-semanal', { token }),
  getEficienciaTiempo: (token) => apiRequest('/stats/eficiencia-tiempo', { token }),
  getRitmoPregunta: (token) => apiRequest('/stats/ritmo-pregunta', { token }),
  getBalancePrecision: (token) => apiRequest('/stats/balance-precision', { token }),
  submit: (token, payload) => apiRequest('/tests/submit', { method: 'POST', body: payload, token }),
  history: (token, params = {}) => apiRequest('/tests/history', { token, query: params }),
  userStats: (token) => apiRequest('/stats/user', { token }),
  temaStats: (token, bloqueId) => apiRequest('/stats/bloque', { token, query: { bloque_id: bloqueId } }),
  repasoStats: (token, bloqueId) => apiRequest('/stats/repaso', { token, query: { bloque_id: bloqueId } }),
  simulacroStats: (token, oposicionId) => apiRequest('/stats/simulacros', { token, query: { oposicion_id: oposicionId } }),
  getDashboard: (token) => apiRequest('/stats/dashboard', { token }),
  getObjetivoDiario: (token) => apiRequest('/stats/objetivo-diario', { token }),
  getGamificacion: (token) => apiRequest('/stats/gamificacion', { token }),
  getRacha: (token) => apiRequest('/stats/racha', { token }),
  getRachaBloques: (token) => apiRequest('/stats/racha-bloques', { token }),
  getResumenOposicion: (token, oposicionId) => apiRequest('/stats/resumen-oposicion', { token, query: { oposicion_id: oposicionId } }),
  getProgresoBloques: (token, oposicionId) => apiRequest('/stats/progreso-bloques', { token, query: oposicionId ? { oposicion_id: oposicionId } : {} }),
  getProgresoBloquesByTema: (token, temaId) => apiRequest('/stats/progreso-bloques-tema', { token, query: { tema_id: temaId } }),
  getProgresoTemaReal: (token, temaId) => apiRequest('/stats/progreso-tema-real', { token, query: { tema_id: temaId } }),
  getDetalleBloque: (token, bloqueId) => apiRequest(`/stats/bloque/${bloqueId}/detalle`, { token }),
  getMisOposiciones: (token) => apiRequest('/stats/mis-oposiciones', { token }),
  getRanking: (token, oposicionId) => apiRequest('/stats/ranking', { token, query: oposicionId ? { oposicion_id: oposicionId } : {} }),
  evolucionStats: (token, limit = 30) => apiRequest('/stats/evolucion', { token, query: { limit } }),
  getRepasoPendientes: (token, limit = 20) => apiRequest('/repaso/pendientes', { token, query: { limit } }),
  getReview: (token, testId) => apiRequest(`/tests/${testId}/review`, { token }),
  getConfig: (token, testId) => apiRequest(`/tests/${testId}/config`, { token }),
};