ALTER TABLE accesos_oposicion ADD CONSTRAINT accesos_oposicion_pkey PRIMARY KEY (id);
ALTER TABLE actividad_global ADD CONSTRAINT actividad_global_pkey PRIMARY KEY (id);
ALTER TABLE admin_tests ADD CONSTRAINT admin_tests_pkey PRIMARY KEY (id);
ALTER TABLE admin_tests_preguntas ADD CONSTRAINT admin_tests_preguntas_pkey PRIMARY KEY (test_id, pregunta_id);
ALTER TABLE auditoria_preguntas ADD CONSTRAINT auditoria_preguntas_pkey PRIMARY KEY (id);
ALTER TABLE colecciones ADD CONSTRAINT temas_pkey PRIMARY KEY (id);
ALTER TABLE colecciones_preguntas ADD CONSTRAINT colecciones_preguntas_pkey PRIMARY KEY (coleccion_id, pregunta_id);
ALTER TABLE configuracion_sistema ADD CONSTRAINT configuracion_sistema_pkey PRIMARY KEY (clave);
ALTER TABLE etiquetas ADD CONSTRAINT etiquetas_pkey PRIMARY KEY (id);
ALTER TABLE notificaciones ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);
ALTER TABLE opciones_respuesta ADD CONSTRAINT opciones_respuesta_pkey PRIMARY KEY (id);
ALTER TABLE oposiciones ADD CONSTRAINT oposiciones_pkey PRIMARY KEY (id);
ALTER TABLE password_resets ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);
ALTER TABLE planificacion_academica_temas ADD CONSTRAINT planificacion_academica_temas_pkey PRIMARY KEY (planificacion_id, tema_id);
ALTER TABLE planificaciones_academicas ADD CONSTRAINT planificaciones_academicas_pkey PRIMARY KEY (id);
ALTER TABLE preguntas ADD CONSTRAINT preguntas_pkey PRIMARY KEY (id);
ALTER TABLE preguntas_etiquetas ADD CONSTRAINT preguntas_etiquetas_pkey PRIMARY KEY (pregunta_id, etiqueta_id);
ALTER TABLE preguntas_marcadas ADD CONSTRAINT preguntas_marcadas_pkey PRIMARY KEY (id);
ALTER TABLE profesores_oposiciones ADD CONSTRAINT profesores_oposiciones_pkey PRIMARY KEY (id);
ALTER TABLE progreso_usuario ADD CONSTRAINT progreso_usuario_pkey PRIMARY KEY (id);
ALTER TABLE repeticion_espaciada ADD CONSTRAINT repeticion_espaciada_pkey PRIMARY KEY (id);
ALTER TABLE reportes_preguntas ADD CONSTRAINT reportes_preguntas_pkey PRIMARY KEY (id);
ALTER TABLE respuestas_usuario ADD CONSTRAINT respuestas_usuario_pkey PRIMARY KEY (id);
ALTER TABLE resultados_test ADD CONSTRAINT resultados_test_pkey PRIMARY KEY (id);
ALTER TABLE simulacros ADD CONSTRAINT simulacros_pkey PRIMARY KEY (id);
ALTER TABLE simulacros_bloques ADD CONSTRAINT simulacros_bloques_pkey PRIMARY KEY (id);
ALTER TABLE simulacros_preguntas ADD CONSTRAINT simulacros_preguntas_pkey PRIMARY KEY (id);
ALTER TABLE suscripciones ADD CONSTRAINT suscripciones_pkey PRIMARY KEY (id);
ALTER TABLE temas ADD CONSTRAINT materias_pkey PRIMARY KEY (id);
ALTER TABLE tests ADD CONSTRAINT tests_pkey PRIMARY KEY (id);
ALTER TABLE tests_preguntas ADD CONSTRAINT tests_preguntas_pkey PRIMARY KEY (id);
ALTER TABLE usuario_oposiciones ADD CONSTRAINT usuario_oposiciones_pkey PRIMARY KEY (id);
ALTER TABLE usuarios ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);
