BEGIN;

UPDATE oposiciones
SET
  nombre = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(nombre,
    'Â¿', '¿'),
    'Â¡', '¡'),
    'Ã¡', 'á'),
    'Ã©', 'é'),
    'Ã­', 'í'),
    'Ã³', 'ó'),
    'Ãº', 'ú'),
    'Ã±', 'ñ'),
    'Ã‘', 'Ñ'),
    'Ã¼', 'ü'),
    'Ãœ', 'Ü'),
    'MonarquÃa', 'Monarquía'),
    'jurÃdico', 'jurídico'),
    'polÃtico', 'político'),
    'soberanÃa', 'soberanía'),
    'ci�n', 'ción'),
    'Ci�n', 'Ción'),
    'a�o', 'año'),
    'A�o', 'Año'),
    '�', ''),
  descripcion = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(descripcion,
    'Â¿', '¿'),
    'Â¡', '¡'),
    'Ã¡', 'á'),
    'Ã©', 'é'),
    'Ã­', 'í'),
    'Ã³', 'ó'),
    'Ãº', 'ú'),
    'Ã±', 'ñ'),
    'Ã‘', 'Ñ'),
    'Ã¼', 'ü'),
    'Ãœ', 'Ü'),
    'MonarquÃa', 'Monarquía'),
    'jurÃdico', 'jurídico'),
    'polÃtico', 'político'),
    'soberanÃa', 'soberanía'),
    'ci�n', 'ción'),
    'Ci�n', 'Ción'),
    'a�o', 'año'),
    'A�o', 'Año'),
    '�', '')
WHERE nombre ~ 'Â|Ã|�|�'
   OR (descripcion IS NOT NULL AND descripcion ~ 'Â|Ã|�|�');

UPDATE materias
SET nombre = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(nombre,
  'Â¿', '¿'),
  'Â¡', '¡'),
  'Ã¡', 'á'),
  'Ã©', 'é'),
  'Ã­', 'í'),
  'Ã³', 'ó'),
  'Ãº', 'ú'),
  'Ã±', 'ñ'),
  'Ã‘', 'Ñ'),
  'Ã¼', 'ü'),
  'Ãœ', 'Ü'),
  'MonarquÃa', 'Monarquía'),
  'jurÃdico', 'jurídico'),
  'polÃtico', 'político'),
  'soberanÃa', 'soberanía'),
  'ci�n', 'ción'),
  'Ci�n', 'Ción'),
  'a�o', 'año'),
  'A�o', 'Año'),
  '�', '')
WHERE nombre ~ 'Â|Ã|�|�';

UPDATE temas
SET nombre = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(nombre,
  'Â¿', '¿'),
  'Â¡', '¡'),
  'Ã¡', 'á'),
  'Ã©', 'é'),
  'Ã­', 'í'),
  'Ã³', 'ó'),
  'Ãº', 'ú'),
  'Ã±', 'ñ'),
  'Ã‘', 'Ñ'),
  'Ã¼', 'ü'),
  'Ãœ', 'Ü'),
  'MonarquÃa', 'Monarquía'),
  'jurÃdico', 'jurídico'),
  'polÃtico', 'político'),
  'soberanÃa', 'soberanía'),
  'ci�n', 'ción'),
  'Ci�n', 'Ción'),
  'a�o', 'año'),
  'A�o', 'Año'),
  '�', '')
WHERE nombre ~ 'Â|Ã|�|�';

UPDATE preguntas
SET
  enunciado = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(enunciado,
    'Â¿', '¿'),
    'Â¡', '¡'),
    'Ã¡', 'á'),
    'Ã©', 'é'),
    'Ã­', 'í'),
    'Ã³', 'ó'),
    'Ãº', 'ú'),
    'Ã±', 'ñ'),
    'Ã‘', 'Ñ'),
    'Ã¼', 'ü'),
    'Ãœ', 'Ü'),
    'MonarquÃa', 'Monarquía'),
    'jurÃdico', 'jurídico'),
    'polÃtico', 'político'),
    'soberanÃa', 'soberanía'),
    'ci�n', 'ción'),
    'Ci�n', 'Ción'),
    'a�o', 'año'),
    'A�o', 'Año'),
    '�', ''),
  explicacion = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(explicacion,
    'Â¿', '¿'),
    'Â¡', '¡'),
    'Ã¡', 'á'),
    'Ã©', 'é'),
    'Ã­', 'í'),
    'Ã³', 'ó'),
    'Ãº', 'ú'),
    'Ã±', 'ñ'),
    'Ã‘', 'Ñ'),
    'Ã¼', 'ü'),
    'Ãœ', 'Ü'),
    'MonarquÃa', 'Monarquía'),
    'jurÃdico', 'jurídico'),
    'polÃtico', 'político'),
    'soberanÃa', 'soberanía'),
    'ci�n', 'ción'),
    'Ci�n', 'Ción'),
    'a�o', 'año'),
    'A�o', 'Año'),
    '�', ''),
  referencia_normativa = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(referencia_normativa,
    'Â¿', '¿'),
    'Â¡', '¡'),
    'Ã¡', 'á'),
    'Ã©', 'é'),
    'Ã­', 'í'),
    'Ã³', 'ó'),
    'Ãº', 'ú'),
    'Ã±', 'ñ'),
    'Ã‘', 'Ñ'),
    'Ã¼', 'ü'),
    'Ãœ', 'Ü'),
    'MonarquÃa', 'Monarquía'),
    'jurÃdico', 'jurídico'),
    'polÃtico', 'político'),
    'soberanÃa', 'soberanía'),
    'ci�n', 'ción'),
    'Ci�n', 'Ción'),
    'a�o', 'año'),
    'A�o', 'Año'),
    '�', '')
WHERE enunciado ~ 'Â|Ã|�|�'
   OR explicacion ~ 'Â|Ã|�|�'
   OR (referencia_normativa IS NOT NULL AND referencia_normativa ~ 'Â|Ã|�|�');

UPDATE opciones_respuesta
SET texto = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(texto,
  'Â¿', '¿'),
  'Â¡', '¡'),
  'Ã¡', 'á'),
  'Ã©', 'é'),
  'Ã­', 'í'),
  'Ã³', 'ó'),
  'Ãº', 'ú'),
  'Ã±', 'ñ'),
  'Ã‘', 'Ñ'),
  'Ã¼', 'ü'),
  'Ãœ', 'Ü'),
  'MonarquÃa', 'Monarquía'),
  'jurÃdico', 'jurídico'),
  'polÃtico', 'político'),
  'soberanÃa', 'soberanía'),
  'ci�n', 'ción'),
  'Ci�n', 'Ción'),
  'a�o', 'año'),
  'A�o', 'Año'),
  '�', '')
WHERE texto ~ 'Â|Ã|�|�';

COMMIT;